### PR TITLE
Task03 Егор Овчинников ITMO

### PR DESCRIPTION
**Pull request by RazerFord**
Фрактал Мандельброта
=========

<details>
<summary>Локальный вывод CPU</summary>
<p>

<pre>
OpenCL devices:
  Device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
  Device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb
  Device #2: CPU. pthread-AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx. AuthenticAMD. Total memory: 11798 Mb
Using device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb

CPU: 0.59719+-0.0118042 s
CPU: 16.7451 GFlops
    Real iterations fraction: 56.2638%

AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx: 0.133777+-0.00177359 s
AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx: 74.7515 GFlops
    Real iterations fraction: 56.2657%

GPU vs CPU average results difference: 0.943129%
</pre>

</p>
</details>

<details>
<summary>Локальный вывод GPU</summary>
<p>

<pre>
OpenCL devices:
  Device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
  Device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb
  Device #2: CPU. pthread-AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx. AuthenticAMD. Total memory: 11798 Mb
Using device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb

CPU: 0.599338+-0.0070044 s
CPU: 16.6851 GFlops
    Real iterations fraction: 56.2638%

NVIDIA GeForce GTX 1650: 0.0046025+-8.92707e-05 s
NVIDIA GeForce GTX 1650: 2172.73 GFlops
    Real iterations fraction: 56.2657%

GPU vs CPU average results difference: 0.942446%
</pre>

</p>
</details>

<details>
<summary>Вывод Github CI</summary>
<p>

<pre>
OpenCL devices:
  Device #0: CPU. Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz. Intel(R) Corporation. Total memory: 6932 Mb
Using device #0: CPU. Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz. Intel(R) Corporation. Total memory: 6932 Mb

CPU: 1.86118+-0.00192979 s
CPU: 5.37293 GFlops
    Real iterations fraction: 56.2638%

Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz: 0.136446+-0.00102933 s
Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz: 73.2889 GFlops
    Real iterations fraction: 56.2657%

GPU vs CPU average results difference: 0.942446%
</pre>
</p>
</details>

Суммирование чисел
==============

<details>
<summary>Локальный вывод CPU</summary>
<p>

<pre>
summation on CPU:     0.273386+-0.000644903 s
summation on CPU:     365.784 millions/s

summation on CPU OMP: 0.0707965+-0.00702931 s
summation on CPU OMP: 1412.5 millions/s

OpenCL devices:
  Device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
  Device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb
  Device #2: CPU. pthread-AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx. AuthenticAMD. Total memory: 11798 Mb
Using device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb

with global atomic add: 0.919662+-0.00104961 s
with global atomic add: 108.736 millions/s

with loop: 0.0289227+-5.02947e-05 s
with loop: 3457.5 millions/s

with loop and coalesced access: 0.0252072+-0.00173373 s
with loop and coalesced access: 3967.13 millions/s

with local memory and global thread: 0.0249712+-0.00137437 s
with local memory and global thread: 4004.62 millions/s

with tree: 0.160949+-0.000554453 s
with tree: 621.315 millions/s
</pre>

</p>
</details>

<details>
<summary>Локальный вывод GPU</summary>
<p>

<pre>
summation on CPU:     0.297369+-0.0156864 s
summation on CPU:     336.282 millions/s

summation on CPU OMP: 0.0678258+-0.00228869 s
summation on CPU OMP: 1474.36 millions/s

OpenCL devices:
  Device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
  Device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb
  Device #2: CPU. pthread-AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx. AuthenticAMD. Total memory: 11798 Mb
Using device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb

with global atomic add: 0.004848+-3.69685e-06 s
with global atomic add: 20627.1 millions/s

with loop: 0.0115545+-0.000226061 s
with loop: 8654.64 millions/s

with loop and coalesced access: 0.003419+-3.74166e-06 s
with loop and coalesced access: 29248.3 millions/s

with local memory and global thread: 0.00424883+-1.48931e-05 s
with local memory and global thread: 23535.9 millions/s

with tree: 0.009664+-1.36991e-05 s
with tree: 10347.7 millions/s
</pre>

</p>
</details>

#### Локальный вывод CPU
| Алгоритм                          | Время, с | Число операций, млн/с |
| :-------------------------------- | :------- | :-------------------- |
| Обычный на CPU                    | 0.273    | 365.784               |
| CPU OMP                           | 0.071    | 1412.5                |
| С глобальным атомарным добалением | 0.920    | 108.736               |
| С циклом                          | 0.029    | 3457.5                |
| С циклом и _coalesced_ доступом   | 0.025    | 3967.13               |
| С _local memory_                  | 0.025    | 4004.62               |
| С помощью дерева                  | 0.161    | 621.315               |

#### Локальный вывод GPU
| Алгоритм                          | Время, с | Число операций, млн/с |
| :-------------------------------- | :------- | :-------------------- |
| Обычный на CPU                    | 0.297    | 336.282               |
| CPU OMP                           | 0.068    | 1474.36               |
| С глобальным атомарным добалением | 0.005    | 20627.1               |
| С циклом                          | 0.012    | 8654.64               |
| С циклом и _coalesced_ доступом   | 0.003    | 29248.3               |
| С _local memory_                  | 0.004    | 23535.9               |
| С помощью дерева                  | 0.009    | 10347.7               |

Самым быстрым оказался алгоритм с _local memory_ для **CPU** и с циклом вместе _coalesced_ доступом к памяти для **GPU**.

Из результатов можно заметить, что алгоритмы с атомарным добавлением для обоих устройств показали наихудшие результаты.

Также не очень оптимальные результаты показали алгоритмы суммирования с помощью дерева, возможно, что это связано с тем, что значительная часть ресурсов тратится на барьерную синхронизацию, а в этом алгоритме она вызывается два раза.

<details>
<summary>Вывод Github CI</summary>
<p>

<pre>
summation on CPU:     0.0751573+-0.00123506 s
summation on CPU:     1330.54 millions/s

summation on CPU OMP: 0.0314622+-0.000956118 s
summation on CPU OMP: 3178.42 millions/s

OpenCL devices:
  Device #0: CPU. Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz. Intel(R) Corporation. Total memory: 6932 Mb
Using device #0: CPU. Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz. Intel(R) Corporation. Total memory: 6932 Mb

with global atomic add: 1.77927+-0.0108572 s
with global atomic add: 56.2028 millions/s

with loop: 0.0601105+-0.000847642 s
with loop: 1663.6 millions/s

with loop and coalesced access: 0.0291253+-0.000353934 s
with loop and coalesced access: 3433.44 millions/s

with local memory and global thread: 0.0689538+-0.000445013 s
with local memory and global thread: 1450.25 millions/s

with tree: 0.17103+-0.000521264 s
with tree: 584.692 millions/s
</pre>
</p>
</details>

#### Вывод Github CI
| Алгоритм                          | Время, с | Число операций, млн/с |
| :-------------------------------- | :------- | :-------------------- |
| Обычный на CPU                    | 0.075    | 1330.54               |
| CPU OMP                           | 0.031    | 3178.42               |
| С глобальным атомарным добалением | 1.779    | 56.2028               |
| С циклом                          | 0.060    | 1663.6                |
| С циклом и _coalesced_ доступом   | 0.029    | 3433.44               |
| С _local memory_                  | 0.069    | 1450.25               |
| С помощью дерева                  | 0.171    | 584.692               |

На **CI** же самым быстрым оказался алгоритм с циклом и _coalesced_ доступом к памяти.

#### Любопытные наблюдения

Сравним выполнения алгоритмов с циклом без и с _coalesced_ доступом при разных значениях **VALUES_PER_WORK_ITEM**.

**VALUES_PER_WORK_ITEM = 128**
| Алгоритм                        | Время, с | Число операций, млн/с |
| :------------------------------ | :------- | :-------------------- |
| С циклом                        | 0.029    | 3457.5                |
| С циклом и _coalesced_ доступом | 0.025    | 3967.13               |

**VALUES_PER_WORK_ITEM = 64**
| Алгоритм                        | Время, с | Число операций, млн/с |
| :------------------------------ | :------- | :-------------------- |
| С циклом                        | 0.021    | 4869.26               |
| С циклом и _coalesced_ доступом | 0.031    | 3206.6                |

Можно заметить, что число операций для алгоритма с циклом без _coalesced_ доступа к памяти стало больше, чем число операций для для алгоритма с _coalesced_ доступом к памяти.

Если посмотреть результаты для **GPU** при уменьшении **VALUES_PER_WORK_ITEM**, то тоже можно заметить, что число операций возрастает.

| Алгоритм | VALUES_PER_WORK_ITEM | Число операций, млн/с |
| :------- | :------------------- | :-------------------- |
| С циклом | 64                   | 12810.1               |
| С циклом | 128                  | 8654.64               |

### CODE REVIEW

**Comment by simiyutin** [comment]
Супер крутые замеры)

> Можно заметить, что число операций для алгоритма с циклом без coalesced доступа к памяти стало больше, чем число операций для для алгоритма с coalesced доступом к памяти.

Вот это немножко странно, не могло случайно получиться что-нибудь вроде того что в .срр файле 128 на 64 поменяли, а в .cl файле VALUES_PER_WORK_ITEM дефайн остался?

**Comment by RazerFord** [comment]
> Супер крутые замеры)
> 
> > Можно заметить, что число операций для алгоритма с циклом без coalesced доступа к памяти стало больше, чем число операций для для алгоритма с coalesced доступом к памяти.
> 
> Вот это немножко странно, не могло случайно получиться что-нибудь вроде того что в .срр файле 128 на 64 поменяли, а в .cl файле VALUES_PER_WORK_ITEM дефайн остался?

Попробовал запустить свое решение на других ПК, получил с `coalesced` быстрее, как и должно быть, но у меня остается по прежнему, что цикл быстрее, чем `coalesced`.

<details>
<summary>Решение на другом ПК с VALUES_PER_WORKITEM=64</summary>
<p>

<pre>
summation on CPU:     0.164656+-0.000480005 s
summation on CPU:     607.328 millions/s

summation on CPU OMP: 0.0320607+-0.000372693 s
summation on CPU OMP: 3119.09 millions/s

OpenCL devices:
  Device #0: GPU. AMD Radeon Graphics (gfx90c:xnack-). Free memory: 486/512 Mb
Using device #0: GPU. AMD Radeon Graphics (gfx90c:xnack-). Free memory: 486/512 Mb

with global atomic add: 0.48268+-0.0381909 s
with global atomic add: 207.177 millions/s

with loop: 0.0628248+-0.00080283 s
with loop: 1591.73 millions/s

with loop and coalesced access: 0.043622+-0.0124532 s
with loop and coalesced access: 2292.42 millions/s

with local memory and global thread: 0.24971+-0.147393 s
with local memory and global thread: 400.465 millions/s

with tree: 0.028456+-0.00109497 s
with tree: 3514.2 millions/s
</pre>

</p>
</details>

Попробовал запустить другое решение, получил также, что обычный цикл без `coalesced` работает быстрее.

<details>
<summary>Другое решение</summary>
<p>

<pre>
CPU:     0.28605+-0.0143679 s
CPU:     349.589 millions/s
CPU OMP: 0.0801215+-0.00256661 s
CPU OMP: 1248.1 millions/s
OpenCL devices:
  Device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
  Device #1: GPU. NVIDIA GeForce GTX 1650. Total memory: 3903 Mb
  Device #2: CPU. pthread-AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx. AuthenticAMD. Total memory: 11798 Mb
Using device #0: CPU. AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  . Intel(R) Corporation. Total memory: 13846 Mb
Atomic: 0.923795+-0.00209642 s
Atomic: 108.249 M/s
Loop: 0.0189702+-0.000338912 s
Loop: 5271.43 M/s
Coalesced loop: 0.031189+-6.85249e-05 s
Coalesced loop: 3206.26 M/s
Local memory loop: 0.0314332+-0.000148055 s
Local memory loop: 3181.35 M/s
Local memory tree: 0.323313+-0.00597874 s
Local memory tree: 309.297 M/s
Global memory tree: 0.385697+-0.00940175 s
Global memory tree: 259.271 M/s
</pre>

</p>
</details>

**Comment by RazerFord** [comment]
> > Супер крутые замеры)
> > > Можно заметить, что число операций для алгоритма с циклом без coalesced доступа к памяти стало больше, чем число операций для для алгоритма с coalesced доступом к памяти.
> > 
> > 
> > Вот это немножко странно, не могло случайно получиться что-нибудь вроде того что в .срр файле 128 на 64 поменяли, а в .cl файле VALUES_PER_WORK_ITEM дефайн остался?
> 
> Попробовал запустить свое решение на других ПК, получил, что цикл с `coalesced` быстрее, как и должно быть. У меня же остается по прежнему, что цикл без `coalesced` быстрее.
> 
> Решение на другом ПК с VALUES_PER_WORKITEM=64
> Попробовал запустить другое решение, получил также, что обычный цикл без `coalesced` работает быстрее.
> 
> Другое решение
> При этом если запускать на видеокарте, то результаты вполне ожидаемые

**Comment by RazerFord** [comment]
Извините, случайно переоткрыл `PR`

**Comment by simiyutin** [comment]
Все хорошо, задача зачтена, 10/10 баллов :+1:

**Pull request closed without merging**
